site_name: ESIIL OASIS
site_description: ESIIL OASIS Documentation
site_author: ESIIL CI team (lead: Ty Tuff)
site_url: https://cu-esiil.github.io/documentation/

# Repository
repo_name: documentation
repo_url: https://github.com/cu-esiil/documentation
edit_uri: edit/main/docs/
# Copyright
copyright: 'Copyright &copy; 2022 - 2023 University of Colorado Boulder'

# Page tree
nav:
  - Main:
    - Home: index.md
    - Status and News: status.md
    - Governance: governance.md
  - Frequently Asked Questions:
    - General FAQs: faq.md
    - Troubleshooting: troubleshooting.md
    - Allocations: allocations.md
    - Security: security.md
  - General:
    - Resources: resources.md
    - Storage: storage.md
  - Infrastructure:
    - OASIS: oasis.md
    - CyVerse: cyverse.md
    - Jetstream-2: js2.md
  - Software:
    - Docker: docker.md
    - ImgSPEC: imgspec.md
    - Jupyter Lab: jupyter.md
    - Jupyter Hub: jupyter_hub.md
    - RStudio: rstudio.md
    - Kubernetes: k8s.md
  - Policies:
    - Acceptable Use: acceptable_use.md
    - Best Practices: best_practice.md
    
# Configuration
theme:
  name: 'material'

  # 404 page
  static_templates:
    - 404.html

  # downloading ipynb notebooks
  custom_dir: "docs/overrides"
    
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Montserrat
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: material/cloud-tags

# Options
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cu-esiil/documentation.git

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          execute_ignore: "notebooks/*.ipynb"
